### PR TITLE
milestone one - Project structure

### PR DESCRIPTION
**Pull request by didymus707**
Here, the app was created with npm react app
- Installed proptypes and big.js and the linters

### CODE REVIEW

**Comment by didymus707** [comment]
The linters are not passing my commits. I had an issue when I was installing the eslint about some incompatible version. I saw an option to force it with a force flag which fixed it. Then I removed the package.lock.json based on advice from someone who faced this issue. The linters are not working correctly on my repo and I am about to allow it waste my time after following every due diligence

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello @didymus707  :wave:

__I appreciate you being open with the challenges you're facing.__

__However, apart from the fact that you need to fix the bug with your linters, some changes are also required before this milestone can be approved.__

__Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [ ] You're required to prepare a descriptive Readme in this milestone. 
- Your app needs to be deployed on Heroku(or other hosts like Netlify, Firebase, etc) and the live link should be included in the README file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone1/app-deployed.png) from [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896085/))
- [ ] About the linter errors, I have a couple of suggestions for you:
- Since the error is about version incompatibility, I'll suggest you identify and remove the affected dependency from the linters run command. 
- You can also identify and remove the affected dependencies from the package.json, delete your `node_modules`, and `package-lock.json, then run `npm install`. After that, try to run the linters command.
- If the issue persists, remove the entire `.github` directory, commit and push your changes.
- Re-setup the GitHub actions by following the instructions as stated [here](https://github.com/microverseinc/linters-config/tree/master/react-redux)
- If there are still errors, try set-up and run linters locally.
- You should also try to understand what the error is talking about. Are there dependency errors, is it a problem with the dependencies version, etc.
- If you're still having challenges, I'll suggest you book a one-on-one session with a Full-Time TSE [here](https://microverse.zendesk.com/hc/en-us/restricted?return_to=https%3A%2F%2Fmicroverse.zendesk.com%2Fhc%2Fen-us%2Farticles%2F360026625973-How-can-I-get-help-from-TSEs-).
- Kindly ensure that all linter checks are passing successfully before you request for another review.





* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Comment by didymus707** [comment]
Seriously, this process for me ain't the best. I removed the package-lock to allow the linters pass as suggested by the tse but deploying to heroku fails with the absence of the package-lock and even still doesn't work well. And it seems till the end of this project, I'm going to be going back and forth on this.

**Review by elmejdki — CHANGES_REQUESTED** [review]
# Status: require changes :recycle: 

Hi, Great job so far :clap: :clap: :+1: :100: I have one simple not for you.

I think you understand the previous TSE wrongly, cause he didn't ask you to remove the package-lock.json permanently but he asked you to remove it and then run npm install which will regenerate it again, please try again returning back the package-lock.json file, and if you have trouble with it contact me on slack to give direct assistance, please.

## Happy Coding :tophat: 
_Feel free to contact me on slack if you have questions or need any kind of help_
**_Zakariae El Mejdki_**

**Review by Forison — APPROVED** [review]
# Status::Approved✔️

# 👋 @didymus707  

#### Good job on addressing the issue raised earlier, kindly merge the branch and proceed to the next task😇.

#### Happy coding👨‍💻

Addo Forison

**Pull request merged**
